### ISSUE TITLE
No longer works on linter 0.3.0

### ISSUE THREAD

**Issue by tomitrescak** [AtomLinter/linter-tslint#23] opened 2015-08-06 05:37 UTC
The linter no longer works. Linter team mentions package deprecation in atom-community/linter#796

**Comment by Arcanemagus** [comment] 2015-08-10 16:37
Duplicate of https://github.com/AtomLinter/linter-tslint/issues/15.

**Comment by park9140** [comment] 2015-09-02 21:24
@tomitrescak, @Arcanemagus.  I threw a quick fix together.  I'm still testing but if you could throw it through its paces I deployed 0.4.0 to apm so you can try it.

**Closed by park9140** 2015-09-02 21:24 UTC
