### ISSUE TITLE
Linter errors are only displayed on the project tab and are not available for just the current active file

### ISSUE THREAD

**Issue by markvandenbrink** [AtomLinter/linter-tslint#30] opened 2015-10-08 10:14 UTC
Hi everyone,

I have a strange problem with tslint. The linter works great, but only for my complete project (or the currently opened files). The file tab remains always empty and the linter warnings are not displayed for the current file:

![151008-tslint](https://cloud.githubusercontent.com/assets/7869636/10363531/4cd53dbe-6db5-11e5-8fca-24493a6a27ad.jpg)

I was wondering if anybody else experienced the same "problem"... Any ideas on what could be the cause?

**Comment by Arcanemagus** [comment] 2015-11-02 18:14
It looks like this is the same bug as https://github.com/palantir/tslint/issues/583, in any case this is a bug from the `tslint` package, not an issue with this linter plugin so I'm marking it as closed.

**Comment by Arcanemagus** [comment] 2015-11-02 18:14
Disregard that comment, it was meant for #33.

**Comment by Arcanemagus** [comment] 2015-11-02 18:23
@markvandenbrink This would only happen if `tslint` for some reason doesn't return the file path when `getFileName()` is called on one of its failure messages. Could you provide steps to reproduce this?

**Comment by davherrmann** [comment] 2015-11-12 17:10
Seems to be a problem related to backslashes in the path - should be specific to Windows:
- `textEditor.getPath()` returns a path with backslashes
- `failure.getFileName()` returns a path with forward slashes

Those two obviously aren't matching...

**Closed** 2015-11-13 17:26 UTC

**Comment by Arcanemagus** [comment] 2015-11-13 17:28
v0.4.3 published which should fix this thanks to @david-driscoll, please file any further issues you find and thanks for reporting this!

**Comment by markvandenbrink** [comment] 2015-11-17 08:19
Sorry for my delayed response. The problem is solved indeed! Thank you all!
