### ISSUE TITLE
Uncaught Error: Channel closed

### ISSUE THREAD

**Issue by CanKer** [AtomLinter/linter-tslint#390] opened 2020-12-22 21:49 UTC
1. Active option "Enable semantic rules"
2. It will disable some rules like "semicolon"
3. Desactive option "Enable semantic rules"
4. these rules won't come as before state
5. To solve that I need to disable linter-tslint and then enable
6. my rules comes back to normal

This problem isn't affecting me because I found solution but maybe it's a bug... 

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.1
**Thrown From**: [linter-tslint](https://github.com/AtomLinter/linter-tslint) package 1.10.43

### Stack Trace

Uncaught Error: Channel closed

```
At events.js:177

Error [ERR_IPC_CHANNEL_CLOSED] [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:678:16)
    at Task.send (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43629)
    at /packages/linter-tslint/lib/workerHelper.js:62:29
    at new Promise (<anonymous>)
    at WorkerHelper.requestJob (/packages/linter-tslint/lib/workerHelper.js:46:12)
    at /packages/linter-tslint/lib/main.js:88:39
    at Generator.next (<anonymous>)
    at step (/packages/linter-tslint/lib/main.js:7:273)
    at /packages/linter-tslint/lib/main.js:7:443
    at new Promise (<anonymous>)
    at /packages/linter-tslint/lib/main.js:7:99
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191492)
    at TextBuffer.saveTo (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:499047)
    at async Promise.all (index 0)
```

### Commands

```
  5x -0:51.1.0 core:save (input.hidden-input)
 16x -0:49.6.0 core:undo (input.hidden-input)
     -0:43.8.0 core:save (input.hidden-input)
     -0:40.8.0 editor:newline (input.hidden-input)
     -0:40.1.0 core:save (input.hidden-input)
     -0:40.1.0 linter:lint (atom-text-editor.editor.is-focused)
  2x -0:39 core:save (input.hidden-input)
     -0:36.5.0 core:backspace (input.hidden-input)
     -0:36.2.0 core:save (input.hidden-input)
     -0:36.2.0 linter:lint (atom-text-editor.editor.is-focused)
  3x -0:35.3.0 core:save (input.hidden-input)
     -0:31.1.0 editor:newline (input.hidden-input)
     -0:28.9.0 core:backspace (input.hidden-input)
     -0:25.4.0 intentions:highlight (input.hidden-input)
  3x -0:24.1.0 core:backspace (input.hidden-input)
  7x -0:19.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angular-auto-import 0.4.1 
angular-snippets 10.0.3 
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-material-ui 2.1.3 
atom-nodejs-snippets 2.1.1 
atom-ternjs 0.20.0 
atom-typescript 14.1.2 
auto-indent 0.5.0 
autoclose-html 0.23.0 
bracket-colorizer 1.4.0 
busy-signal 2.0.1 
Chromo-Color-Previews 1.8.3 
declarations 1.1.3 
declarations-js 1.0.2 
editorconfig 2.6.1 
expressjs 2.2.0 
file-icons 2.1.46 
fold-functions 0.11.0 
git-blame 1.8.0 
git-plus 8.7.1 
goto-definition 1.3.4 
highlight-selected 0.17.0 
hyperclick 0.1.5 
ide-php 0.7.18 
intentions 1.1.5 
language-dotenv 1.2.0 
language-ejs 0.4.0 
language-graphql 1.0.0 
laravel 0.7.1 
linter 3.1.1 
linter-csslint 2.0.6 
linter-erb 1.1.5 
linter-eslint 8.5.5 
linter-swagger 0.6.1 
linter-tslint 1.10.43 
linter-ui-default 2.3.0 
platformio-ide-terminal 2.10.1 
prettier-atom 0.60.1 
react 0.18.0 
react-snippets 1.2.0 
remote-atom 1.3.12 
seti-syntax 1.2.0 
seti-ui 1.11.0 
Stylus 3.2.0 
teletype 0.13.4 
turbo-javascript 1.4.0 
xml-formatter 0.13.0 
xml-tools 0.2.1 
Zen 0.18.0 
```

**Comment by aminya** [comment] 2021-04-05 10:42
Duplicate of #387

**Closed by aminya** 2021-04-05 10:42 UTC
