### ISSUE TITLE
update to latest tslint?

### ISSUE THREAD

**Issue by dcsan** [AtomLinter/linter-tslint#88] opened 2016-05-08 05:30 UTC
I'm getting an error which is apparently due to linter-tslint being out of date with tslint itself... 

if i understand correctly

https://github.com/AtomLinter/linter-tslint/issues/87#issuecomment-217673591

> That rule first appeared in tslint@3.7.0-dev.1. linter-tslint v0.9.1 only includes tslint@3.6.0.
> If you update to the latest version you will be updated to tslint@3.8.1 and it should then know about that rule.

**Comment by Arcanemagus** [comment] 2016-05-08 06:52
Closing as a duplicate of #87.

**Closed by Arcanemagus** 2016-05-08 06:52 UTC
