### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by thaingnguyen** [AtomLinter/linter-tslint#19] opened 2015-07-09 15:41 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
Object.activate (C:\Users\t-thangu\.atom\packages\linter\lib\main.coffee:57:8)
Package.activateNow (C:\Users\t-thangu\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:240:19)
<unknown> (C:\Users\t-thangu\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:221:30)
Package.measure (C:\Users\t-thangu\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:165:15)
Package.activate (C:\Users\t-thangu\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:213:14)
PackageManager.activatePackage (C:\Users\t-thangu\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package-manager.js:452:21)
```

**Comment by faddah** [comment] 2015-07-18 16:58
+1, seeing this also.

—  faddah
     portland, oregon, u.s.a.

**Comment by jtrinklein** [comment] 2015-07-20 19:27
Seeing the same issue as well.

**Comment by mrmckeb** [comment] 2015-07-28 05:16
+1

**Comment by ChadStrat** [comment] 2015-08-06 15:24
+1

**Comment by Arcanemagus** [comment] 2015-08-10 16:36
Duplicate of https://github.com/AtomLinter/linter-tslint/issues/15.

**Comment by park9140** [comment] 2015-09-02 21:28
@mrmckeb, @ChadStrat, @faddah, @thaingnguyen,  I threw a quick fix together.  I'm still testing but if you could throw it through its paces I deployed 0.4.0 to apm so you can try it.  Report issues on #21

**Closed by park9140** 2015-09-02 21:28 UTC
