### ISSUE TITLE
tslint doesn't honor lintOnChange

### ISSUE THREAD

**Issue by jfrancos** [AtomLinter/linter-tslint#220] opened 2018-03-02 17:12 UTC
I have "Lint on Change" set in Linter, and this works fine with eslint. But for tslint, linting does not seem to happen until I save the file.

**Comment by AlexanderOMara** [comment] 2018-03-28 19:47
If you have the semantic rules option enabled, I suspect #222 details your issue.

**Comment by madhums** [comment] 2019-02-20 23:54
Perhaps it is related to this piece of code https://github.com/AtomLinter/linter-tslint/blob/master/lib/main.js#L146

```js
  // ...
  provideLinter() {
    return {
      name: 'TSLint',
      grammarScopes,
      scope: 'file',
      lintsOnChange: true, // <-- This should probably read from atom.config?
      lint: async (textEditor) => {
  // ...
```

I suppose the line that reads `lintsOnChange: true` should read from `atom.config`?

**Comment by Arcanemagus** [comment] 2019-02-21 00:11
I'm not sure what you are trying to say there... this provider doesn't have a setting to override that.

I'm going to assume that @AlexanderOMara was correct in their assumption that this is a duplicate of #222. Since @jfrancos never responded though we'll likely never know for sure.

**Closed by Arcanemagus** 2019-02-21 00:11 UTC
